source 'https://cdn.cocoapods.org/'

project 'Examples-CocoaPods'

target 'Analytics-iOS' do
  platform :ios, '10.0'
  pod 'BrazeKit'
end

target 'Analytics-tvOS' do
  platform :tvos, '10.0'
  pod 'BrazeKit'
end

target 'InAppMessages' do
  platform :ios, '10.0'
  pod 'BrazeKit'
  pod 'BrazeUI'
  pod 'SDWebImage', :modular_headers => true
end

target 'Location-iOS' do
  platform :ios, '10.0'
  pod 'BrazeKit'
  pod 'BrazeLocation'
end

target 'Location-tvOS' do
  platform :tvos, '10.0'
  pod 'BrazeKit'
  pod 'BrazeLocation'
end

target 'PushNotifications' do
  platform :ios, '10.0'
  pod 'BrazeKit'
end

target 'PushNotificationsServiceExtension' do
  platform :ios, '10.0'
  pod 'BrazeNotificationService'
end

target 'PushNotificationsContentExtension' do
  platform :ios, '10.0'
  pod 'BrazePushStory'
end
